-- MySQL Script generated by MySQL Workbench
-- Tue May 28 08:14:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Boite_a_outils_pour_electronicien
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Boite_a_outils_pour_electronicien` ;

-- -----------------------------------------------------
-- Schema Boite_a_outils_pour_electronicien
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Boite_a_outils_pour_electronicien` DEFAULT CHARACTER SET utf8 ;
USE `Boite_a_outils_pour_electronicien` ;

-- -----------------------------------------------------
-- Table `Boite_a_outils_pour_electronicien`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boite_a_outils_pour_electronicien`.`supplier` ;

CREATE TABLE IF NOT EXISTS `Boite_a_outils_pour_electronicien`.`supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(216) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idSupplier_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boite_a_outils_pour_electronicien`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boite_a_outils_pour_electronicien`.`product` ;

CREATE TABLE IF NOT EXISTS `Boite_a_outils_pour_electronicien`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  `value` FLOAT NOT NULL,
  `Size` FLOAT NOT NULL,
  `price` FLOAT NOT NULL,
  `manufacturer-reference` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idproduct_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Manufacturer-reference_UNIQUE` (`manufacturer-reference` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boite_a_outils_pour_electronicien`.`product_has_supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boite_a_outils_pour_electronicien`.`product_has_supplier` ;

CREATE TABLE IF NOT EXISTS `Boite_a_outils_pour_electronicien`.`product_has_supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `article_number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`, `product_id`, `supplier_id`),
  INDEX `fk_product_has_Supplier_Supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_product_has_Supplier_product_idx` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_Supplier_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `Boite_a_outils_pour_electronicien`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_product_has_Supplier_Supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Boite_a_outils_pour_electronicien`.`supplier` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
