-- MySQL Script generated by MySQL Workbench
-- Fri May 17 08:02:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Boite_a_outils_pour_electronicien
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Boite_a_outils_pour_electronicien` ;

-- -----------------------------------------------------
-- Schema Boite_a_outils_pour_electronicien
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Boite_a_outils_pour_electronicien` DEFAULT CHARACTER SET utf8 ;
USE `Boite_a_outils_pour_electronicien` ;

-- -----------------------------------------------------
-- Table `Boite_a_outils_pour_electronicien`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boite_a_outils_pour_electronicien`.`supplier` ;

CREATE TABLE IF NOT EXISTS `Boite_a_outils_pour_electronicien`.`supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(216) NOT NULL,
  `PhoneNumber` INT NOT NULL,
  PRIMARY KEY (`idSupplier`),
  UNIQUE INDEX `idSupplier_UNIQUE` (`idSupplier` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boite_a_outils_pour_electronicien`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boite_a_outils_pour_electronicien`.`product` ;

CREATE TABLE IF NOT EXISTS `Boite_a_outils_pour_electronicien`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `Type` INT NOT NULL,
  `Value` FLOAT NOT NULL,
  `Size` FLOAT NOT NULL,
  `Price` FLOAT NOT NULL,
  `Manufacturer-reference` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idproduct`),
  UNIQUE INDEX `idproduct_UNIQUE` (`idproduct` ASC) VISIBLE,
  UNIQUE INDEX `Manufacturer-reference_UNIQUE` (`Manufacturer-reference` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Boite_a_outils_pour_electronicien`.`product_has_supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Boite_a_outils_pour_electronicien`.`product_has_supplier` ;

CREATE TABLE IF NOT EXISTS `Boite_a_outils_pour_electronicien`.`product_has_supplier` (
  `product_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `Article_number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`product_id`, `supplier_id`),
  INDEX `fk_product_has_Supplier_Supplier1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_product_has_Supplier_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_Supplier_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `Boite_a_outils_pour_electronicien`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_Supplier_Supplier1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `Boite_a_outils_pour_electronicien`.`supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
